files/urls.py
from django.urls import path
from files import views

urlpatterns = [
    path('album/<int:alb_id>', views.album),
    path('album/<int:alb_id>/edit', views.edit_album),
    path('album/<int:alb_id>/delete', views.delete_album),
    path('album/<int:alb_id>/upload/', views.image_upload_view),
    path('album/<int:alb_id>/image/<int:img_id>/edit', views.edit_image),
    path('album/<int:alb_id>/image/<int:img_id>/delete', views.delete_image),
    path('post/', views.post),
    path('', views.home),
    path('register/', views.RegisterFormView.as_view()),
    path('login/', views.LoginFormView.as_view()),
    path('logout/', views.LogoutView.as_view())
]

photosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('files.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


files/models.py
from django.db import models


class Album(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=150)
    author = models.CharField(max_length=150)

    class Meta:
        ordering = ['title']


class Image(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    title = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images')
    album_id = models.ForeignKey(Album, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']

files/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'album_id', 'image')

files/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Album, Image
from .forms import ImageForm
from django.core.paginator import Paginator


def image_upload_view(request, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
    except Album.DoesNotExist:
        return redirect('/')
    if request.user.is_authenticated and request.user.username == album.author:
        if request.method == 'POST':
            form = ImageForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('/album/' + str(alb_id))
        else:
            form = ImageForm()
            return render(request, 'upload.html', {'form': form, 'album': album, 'alb_id': alb_id})

    else:
        return redirect('/')


def post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            title = request.POST.get('title')
            description = request.POST.get('description')
            author = request.POST.get('author')
            Album.objects.create(
                title=title,
                description=description,
                author=author
            )
            return redirect('/')
        return render(request, 'post.html')
    else:
        return redirect('/')


def edit_image(request, img_id, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
        image = Image.objects.get(id=img_id)
    except Image.DoesNotExist:
        return redirect('/')
    if request.user.username == album.author:
        if request.method == "POST":
            image.title = request.POST.get('title')
            image.save()
            return redirect('/album/' + str(alb_id))
        else:
            return render(request, "edit_image.html", {'image': image, 'album': album})
    else:
        return redirect('/')
    return render(request, 'edit_image.html')


def edit_album(request, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
    except Album.DoesNotExist:
        return redirect('/')
    if request.user.username == album.author:
        if request.method == "POST":
            album.title = request.POST.get('title')
            album.description = request.POST.get('description')
            album.save()
            return redirect('/album/' + str(alb_id))
        else:
            return render(request, "edit_album.html", {"album": album})
    else:
        return redirect('/')
    return render(request, 'edit_album.html')


def delete_album(request, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
        if request.user.username == album.author:
            album.delete()
            return redirect('/')
        else:
            return redirect('/')
    except Album.DoesNotExist:
        return redirect('/')


def delete_image(request, img_id, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
        image = Image.objects.get(id=img_id)
    except Album.DoesNotExist:
        return redirect('/')
    if request.user.username == album.author:
        image.delete()
        return redirect('/album/' + str(alb_id))
    else:
        return redirect('/')


def album(request, alb_id):
    try:
        album = Album.objects.get(id=alb_id)
    except Album.DoesNotExist:
        return redirect('/')

    images = Image.objects.filter(album_id=alb_id)
    paginator = Paginator(images, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    return render(request, 'album.html', context={
        'album': album,
        'images': page,
        'alb_id': alb_id,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    })


def home(request):
    albums = Album.objects.all()
    return render(request, 'index.html', {
        'albums': albums
    })


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")

templates/album.html
{% extends "base.html" %}

{% block title %}{{ album.title }}{% endblock %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1>{{ album.title }}</h1>
        <p class="lead text-muted">{{ album.description }}</p>
        {% if user.username == album.author %}
        <a href="/album/{{ alb_id }}/upload" class="btn btn-primary my-2">Add photos in album</a>
        <a href="/album/{{ alb_id }}/edit" class="btn btn-info my-2">Edit title and description</a>
        {% endif %}
        <a href="/" class="btn btn-secondary my-2">Back to home</a>
    </div>
</section>
<div class="container list-group">
    {% for image in images.object_list %}
    <div class="list-group-item d-flex">
        {% load thumbnail %}
        {% thumbnail image.image "200" as im %}
            <a href="{{ image.image.url }}" class="img-thumbnail">
              <img src="{{ im.url }}" width="35" height="35">
              <a href="{{ image.image.url }}" class="list-group-item-action align-text-middle clip text-center" style="text-overflow: ellipsis; padding: 10px;">{{ image.title }}</a>
            </a>
        {% endthumbnail %}
        {% if user.username == album.author %}
        <div class="btn-group">
            <button class="btn-sm btn-outline-info custom" onclick="document.location='{{ album.id }}/image/{{ image.id }}/edit'">Edit</button>
            <button class="btn-sm ml-sm-2 btn-outline-danger custom" onclick="document.location='{{ album.id }}/image/{{ image.id }}/delete'">Delete</button>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    <br>
    {% if is_paginated %}
        <nav aria-label="..." class="m-auto">
            <ul class="pagination ">
                <li class="page-item {% if not prev_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                    {% for n in images.paginator.page_range %}
                        {% if images.number == n %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
                            </li>
                        {% elif n > images.number|add:-3 and n < images.number|add:3 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                <li class="page-item {% if not next_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Next</a>
                </li>
            </ul>
        </nav>
    {% endif%}
</div>

<style>
    a.clip {
        white-space: nowrap; /* Запрещаем перенос строк */
        overflow: hidden; /* Обрезаем все, что не помещается в область */
        text-overflow: ellipsis; /* Добавляем многоточие */
    }
</style>

{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


    </style>
    <title>{% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" href="{% static 'js/main.js' %}"></script>
</head>

<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container-sm d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                     viewBox="0 0 24 24" focusable="false">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Photosite</strong>
            </a>
            <div class="text-white text-right ">
                {% if user.is_authenticated %}
                <i>Hello <span style="color: yellow;"> {{ user.username }}</span>!</i>
                {% else %}
                <i>Welcome!</i>
                {% endif %}
            </div>
        </div>

    </div>
</header>

{% block content %}{% endblock %}
<footer class="text-muted">
    <div class="container justify-content-between">
        <p class="text-center">The site was specially developed for the company "MITKOM"
            <br>Copyright 2020 - All Right Reserved</p>
    </div>
</footer>
</body>
</html>

templates/edit_album.html
{% extends "base.html" %}

{% block title %}Edit album{% endblock %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Edit album</h1>
        <p class="lead text-muted">This you can edit album</p>
        <a href="/" class="btn btn-secondary my-2">Back to home</a>
    </div>
</section>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="hidden" name="author" id="Author" value="{{ user.username }}" readonly required>
        </div>
        <div class="form-group">
            <label for="Album title">Album title:</label>
            <input class="form-control" type="text" name="title" maxlength="20" id="Album title" value="{{ album.title }}" required>
        </div>
        <div class="form-group">
            <label for="Album description">Album description:</label>
            <textarea class="form-control" name="description" id="Album description" maxlength="150" required>{{ album.description }}</textarea>
        </div>
        <button class="btn btn-lg btn-primary">Edit</button>
    </form>
</div>
{% endblock %}

templates/edit_image.html
{% extends "base.html" %}

{% block title %}Edit photo{% endblock %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>{{ album.title }}</h1>
        <p class="lead text-muted">{{ album.description }}</p>
        <a href="/album/{{ album.id }}" class="btn btn-secondary my-2">Back to album</a>
    </div>
</section>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Photo title:</label>
            <input type="text" name="title" maxlength="50" required="" id="id_title" value="{{ image.title }}">
        </div>
        <button type="submit" class="btn btn-lg btn-primary">Edit</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home page{% endblock %}

{% block content %}

<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1>Album list</h1>
            <p class="lead text-muted">Below are various photo albums. In order to add an album, you must be logged in. For unauthorized users, only viewing photos in albums is available.</p>
            <p>
                {% if user.is_authenticated %}
                    <a href="/post" class="btn btn-primary my-2">Add albums</a>
                    <a href="/logout" class="btn btn-secondary my-2">Log out</a>
                {% else %}
                    <a href="/register" class="btn btn-primary my-2">Sign up</a>
                    <a href="/login" class="btn btn-primary my-2">Log in</a>
                {% endif %}
            </p>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for album in albums %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Album title</title>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em" class="clip">{{ album.title }}</text>
                            </svg>
                            <div class="card-body">
                                <p class="card-text clip">{{ album.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button onclick="document.location='album/{{ album.id }}'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        {% if user.username == album.author %}
                                            <button onclick="document.location='album/{{ album.id }}/delete'" type="button" class="btn btn-sm btn-outline-danger">Delete</button>
                                        {% endif %}
                                    </div>
                                    <small class="text-muted">{{ album.author }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
<style>
    p.clip {
        white-space: nowrap; /* Запрещаем перенос строк */
        overflow: hidden; /* Обрезаем все, что не помещается в область */
        text-overflow: ellipsis; /* Добавляем многоточие */
    }
</style>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Home page{% endblock %}

{% block content %}

<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1>Album list</h1>
            <p class="lead text-muted">Below are various photo albums. In order to add an album, you must be logged in. For unauthorized users, only viewing photos in albums is available.</p>
            <p>
                {% if user.is_authenticated %}
                    <a href="/post" class="btn btn-primary my-2">Add albums</a>
                    <a href="/logout" class="btn btn-secondary my-2">Log out</a>
                {% else %}
                    <a href="/register" class="btn btn-primary my-2">Sign up</a>
                    <a href="/login" class="btn btn-primary my-2">Log in</a>
                {% endif %}
            </p>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for album in albums %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Album title</title>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em" class="clip">{{ album.title }}</text>
                            </svg>
                            <div class="card-body">
                                <p class="card-text clip">{{ album.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button onclick="document.location='album/{{ album.id }}'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        {% if user.username == album.author %}
                                            <button onclick="document.location='album/{{ album.id }}/delete'" type="button" class="btn btn-sm btn-outline-danger">Delete</button>
                                        {% endif %}
                                    </div>
                                    <small class="text-muted">{{ album.author }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
<style>
    p.clip {
        white-space: nowrap; /* Запрещаем перенос строк */
        overflow: hidden; /* Обрезаем все, что не помещается в область */
        text-overflow: ellipsis; /* Добавляем многоточие */
    }
</style>

{% endblock %}

templates/post.html
{% extends "base.html" %}

{% block title %}Add album{% endblock %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Add new album</h1>
        <p class="lead text-muted">The album you create can be viewed by all users, but only you can edit</p>
        <a href="/" class="btn btn-secondary my-2">Back to home</a>
    </div>
</section>
<div class="container">
    <p class="text-warning">{{ error }}</p>
    <form action="/post/" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="hidden" name="author" id="Author" value="{{ user.username }}" readonly required>
        </div>
        <div class="form-group">
            <label for="Album title">Album title:</label>
            <input class="form-control" type="text" name="title" id="Album title" maxlength="20" placeholder="Your title..." required>
        </div>
        <div class="form-group">
            <label for="Album description">Album description:</label>
            <textarea class="form-control" name="description" id="Album description" maxlength="150" placeholder="Your description..." required></textarea>
        </div>
        <button class="btn btn-lg btn-primary">Add</button>
    </form>
</div>
{% endblock %}

templates/register.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" href="{% static 'js/main.js' %}"></script>
    <title>Sign up</title>
</head>

<body class="text-center">
<div class="container align-middle custom-c">
    <form class="form-signin" action="" method="post">
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="none" stroke="currentColor"
             stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
             viewBox="0 0 24 24" focusable="false">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
            <circle cx="12" cy="13" r="4"/>
        </svg>
        <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        <br>
        <a href="/login">Log in</a> or <a href="/">Back</a>
    </form>
</div>
</body>
</html>

<style>
    form {
        margin: 10% 10% 5%;
    }

    span.helptext {
        display: block;
        font-style: italic;
        color: #007bff;
    }

    custom-c {
        margin: 200px;
    }

    ul.errorlist>li {
        color: #dc3545;
    }

    ul {
        padding: 0px;
        font-style: italic;
        color: #007bff;
    }

    ul>li {
        list-style-type: none;
    }
</style>

templates/upload.html
{% extends "base.html" %}

{% block title %}Upload photo{% endblock %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1>{{ album.title }}</h1>
        <p class="lead text-muted">{{ album.description }}</p>
        <a href="/album/{{alb_id}}" class="btn btn-secondary my-2">Back to album</a>
    </div>
</section>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Photo title:</label>
            <input type="text" name="title" maxlength="128" required="" id="id_title">
        </div>
        <div class="form-group">
            <input class="form-control" type="hidden" name="album_id" id="id_album_id" value="{{ alb_id }}" readonly>
        </div>
        <div class="form-group">
            <label for="id_image">Image:</label>
            <input type="file" name="image" accept="image/*" required="" id="id_image">
        </div>
        <button type="submit" class="btn btn-lg btn-primary">Upload</button>
    </form>
</div>
{% endblock %}